# Generated by Django 5.1.1 on 2024-09-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_curso_profesor_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='main.profesor'),
        ),
    ]
